module.exports = {
  title: "使用 LWJGL 3 开发 3D 游戏",
  base: "/",
  serviceWorker: true,
  markdown: {
    lineNumbers: true,
    externalLinks: { target: "_blank" },
  },
  themeConfig: {
    docsRepo: "CraftStarStudio/wjglbook-bookcontents-zh_CN",
    docsBranch: "master",
    editLinks: true,
    editLinkText: "帮助我们完善这个页面",
    sidebar: [
      ["/", "封面"],
      ["/INTRODUCTION.md", "简介"],
      "/SUMMARY.md",
      "/chapter01/chapter1.md",
      "/chapter02/chapter2.md",
      "/chapter03/chapter3.md",
      "/chapter04/chapter4.md",
      "/chapter05/chapter5.md",
      "/chapter06/chapter6.md",
      "/chapter07/chapter7.md",
      "/chapter08/chapter8.md",
      "/chapter09/chapter9.md",
      "/chapter10/chapter10.md",
      "/chapter11/chapter11.md",
      "/chapter12/chapter12.md",
      "/chapter13/chapter13.md",
      "/chapter14/chapter14.md",
      "/chapter15/chapter15.md",
      "/chapter16/chapter16.md",
      "/chapter17/chapter17.md",
      "/chapter18/chapter18.md",
      "/chapter19/chapter19.md",
      "/chapter20/chapter20.md",
      "/chapter21/chapter21.md",
      "/chapter22/chapter22.md",
      "/chapter23/chapter23.md",
      "/chapter24/chapter24.md",
      "/chapter25/chapter25.md",
      "/chapter26/chapter26.md",
      "/chapter27/chapter27.md",
      "/chapter28/chapter28.md",
    ],
    lastUpdated: "最后更新 ",
    smoothScroll: true,
  },
  evergreen: true,
};
